name: node_flow

on:
  push:
    branches:
      - node_flow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
      
      - name: Install
        run: npm ci
      
      - name: Build static files
        run: npm run build
      
      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        with:
          fileOutput: 'json'
      
      - name: Show files changed
        run: cat $HOME/files.json
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
          clean: true
          single-commit: true