name: Container-2
on:
  push:
    branches:
      - service_container

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - name: test redis connection
        run: |
          cat /etc/os-release
          telnet localhost 6379